server:
  port: 8193
  servlet:
    context-path: /fitness-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/subsdb
    username: postgres
    password: 123
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#sring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/fs
#    username: root
#    password: 123321
#  flyway:
#    url: jdbc:mysql://localhost:3306/fs
#    user: root
#    password: 123321
#    locations: classpath:db/migration
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    open-in-view: false
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false