server:
  port: 8080
  servlet:
    context-path: /fitness-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/subsdb
    username: postgres
    password: 123321
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    url: jdbc:postgresql://localhost:5432/subsdb
    user: postgres
    password: 123321
    locations: classpath:db/migration
